from fastapi.templating import Jinja2Templates

DATABASE_PATH = "assets.db"
APP_TITLE = "WMS 仓储管理系统"

# 原有资产状态
ASSET_STATUS_IN_USE = "in_use"
ASSET_STATUS_IDLE = "idle"
ASSET_STATUS_SCRAPPED = "scrapped"
ASSET_STATUSES = [ASSET_STATUS_IN_USE, ASSET_STATUS_IDLE, ASSET_STATUS_SCRAPPED]
ASSET_STATUS_LABELS = {
    ASSET_STATUS_IN_USE: "使用中",
    ASSET_STATUS_IDLE: "闲置",
    ASSET_STATUS_SCRAPPED: "已报废",
}

# 库区类型
AREA_TYPE_AMBIENT = "ambient"
AREA_TYPE_COLD = "cold"
AREA_TYPE_HAZARDOUS = "hazardous"
AREA_TYPES = [AREA_TYPE_AMBIENT, AREA_TYPE_COLD, AREA_TYPE_HAZARDOUS]
AREA_TYPE_LABELS = {
    AREA_TYPE_AMBIENT: "常温",
    AREA_TYPE_COLD: "冷藏",
    AREA_TYPE_HAZARDOUS: "危险品",
}

# 库位状态
LOCATION_STATUS_EMPTY = "empty"
LOCATION_STATUS_OCCUPIED = "occupied"
LOCATION_STATUS_FROZEN = "frozen"
LOCATION_STATUSES = [LOCATION_STATUS_EMPTY, LOCATION_STATUS_OCCUPIED, LOCATION_STATUS_FROZEN]
LOCATION_STATUS_LABELS = {
    LOCATION_STATUS_EMPTY: "空闲",
    LOCATION_STATUS_OCCUPIED: "占用",
    LOCATION_STATUS_FROZEN: "冻结",
}
LOCATION_STATUS_COLORS = {
    LOCATION_STATUS_EMPTY: "#34C759",
    LOCATION_STATUS_OCCUPIED: "#FF9500",
    LOCATION_STATUS_FROZEN: "#FF3B30",
}

# SKU ABC分类
ABC_CLASS_A = "A"
ABC_CLASS_B = "B"
ABC_CLASS_C = "C"
ABC_CLASSES = [ABC_CLASS_A, ABC_CLASS_B, ABC_CLASS_C]

# 往来单位类型
PARTNER_TYPE_SUPPLIER = "supplier"
PARTNER_TYPE_CUSTOMER = "customer"
PARTNER_TYPE_BOTH = "both"
PARTNER_TYPES = [PARTNER_TYPE_SUPPLIER, PARTNER_TYPE_CUSTOMER, PARTNER_TYPE_BOTH]
PARTNER_TYPE_LABELS = {
    PARTNER_TYPE_SUPPLIER: "供应商",
    PARTNER_TYPE_CUSTOMER: "客户",
    PARTNER_TYPE_BOTH: "供应商/客户",
}

# 容器类型
CONTAINER_TYPE_PALLET = "pallet"
CONTAINER_TYPE_TOTE = "tote"
CONTAINER_TYPE_RACK = "rack"
CONTAINER_TYPES = [CONTAINER_TYPE_PALLET, CONTAINER_TYPE_TOTE, CONTAINER_TYPE_RACK]
CONTAINER_TYPE_LABELS = {
    CONTAINER_TYPE_PALLET: "托盘",
    CONTAINER_TYPE_TOTE: "周转箱",
    CONTAINER_TYPE_RACK: "货架",
}
CONTAINER_STATUS_IDLE = "idle"
CONTAINER_STATUS_IN_USE = "in_use"
CONTAINER_STATUS_DAMAGED = "damaged"

# 入库状态（收货单）
RECEIPT_STATUS_PENDING = "pending"               # 待质检
RECEIPT_STATUS_QC_DONE = "qc_done"               # 完成质检
RECEIPT_STATUS_PENDING_PUTAWAY = "pending_putaway"  # 待上架
RECEIPT_STATUS_CONFIRMED = "confirmed"           # 已入库
RECEIPT_STATUSES = [RECEIPT_STATUS_PENDING, RECEIPT_STATUS_QC_DONE, RECEIPT_STATUS_PENDING_PUTAWAY, RECEIPT_STATUS_CONFIRMED]
RECEIPT_STATUS_LABELS = {
    RECEIPT_STATUS_PENDING: "待质检",
    RECEIPT_STATUS_QC_DONE: "完成质检",
    RECEIPT_STATUS_PENDING_PUTAWAY: "待上架",
    RECEIPT_STATUS_CONFIRMED: "已入库",
}

# 入库类型
RECEIPT_TYPE_PURCHASE = "purchase"
RECEIPT_TYPE_RETURN = "return"
RECEIPT_TYPE_TRANSFER = "transfer"
RECEIPT_TYPE_SURPLUS = "surplus"
RECEIPT_TYPE_GIFT = "gift"
RECEIPT_TYPES = [RECEIPT_TYPE_PURCHASE, RECEIPT_TYPE_RETURN, RECEIPT_TYPE_TRANSFER, RECEIPT_TYPE_SURPLUS, RECEIPT_TYPE_GIFT]
RECEIPT_TYPE_LABELS = {
    RECEIPT_TYPE_PURCHASE: "采购入库",
    RECEIPT_TYPE_RETURN: "退货入库",
    RECEIPT_TYPE_TRANSFER: "调拨入库",
    RECEIPT_TYPE_SURPLUS: "盘盈入库",
    RECEIPT_TYPE_GIFT: "赠品入库",
}

# 出库类型
SO_TYPE_SALE = "sale"
SO_TYPE_PICKING = "picking"
SO_TYPE_TRANSFER = "transfer"
SO_TYPES = [SO_TYPE_SALE, SO_TYPE_PICKING, SO_TYPE_TRANSFER]
SO_TYPE_LABELS = {
    SO_TYPE_SALE: "销售出库",
    SO_TYPE_PICKING: "领料出库",
    SO_TYPE_TRANSFER: "调拨出库",
}

# 盘点类型
COUNT_TYPE_OPEN = "open"
COUNT_TYPE_BLIND = "blind"
COUNT_TYPE_CYCLE = "cycle"
COUNT_TYPE_MOVEMENT = "movement"
COUNT_TYPES = [COUNT_TYPE_OPEN, COUNT_TYPE_BLIND, COUNT_TYPE_CYCLE, COUNT_TYPE_MOVEMENT]
COUNT_TYPE_LABELS = {
    COUNT_TYPE_OPEN: "明盘",
    COUNT_TYPE_BLIND: "盲盘",
    COUNT_TYPE_CYCLE: "循环盘点",
    COUNT_TYPE_MOVEMENT: "动碰盘点",
}

# 冻结类型
BLOCK_TYPE_QC = "qc"
BLOCK_TYPE_ABNORMAL = "abnormal"
BLOCK_TYPE_OTHER = "other"
BLOCK_TYPES = [BLOCK_TYPE_QC, BLOCK_TYPE_ABNORMAL, BLOCK_TYPE_OTHER]
BLOCK_TYPE_LABELS = {
    BLOCK_TYPE_QC: "质检冻结",
    BLOCK_TYPE_ABNORMAL: "异常锁定",
    BLOCK_TYPE_OTHER: "其他",
}

# 交易类型
TRANS_TYPE_INBOUND = "inbound"
TRANS_TYPE_OUTBOUND = "outbound"
TRANS_TYPE_MOVE = "move"
TRANS_TYPE_FREEZE = "freeze"
TRANS_TYPE_RELEASE = "release"
TRANS_TYPE_COUNT_ADJUST = "count_adjust"

# 效期预警默认天数
DEFAULT_EXPIRY_WARNING_DAYS = 30

templates = Jinja2Templates(directory="templates")
